name: Build font

on: 
  push:
    # do not run when push tag
    branches:
        - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install sys tools/deps
      run: |
        sudo pip install gftools

    - name: Build font
      run: gftools builder sources/config.yaml

    # Recording files
    - name: Archive built TTFs
      uses: actions/upload-artifact@v4
      with:
        name: result_ttf
        path: fonts/TTF/**

    - name: Commit fonts
      if: github.event_name == 'workflow_dispatch'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Bump version to ${{ env.VERSION_TAG }}
        file_pattern: 'fonts/TTF/*.ttf'
